import { Jost } from "next/font/google"
import './globals.scss';
import MainHeader from '@/components/main-header/main-header';
import { SubmissionFormProvider } from "@/context/SubmissionFormProvider";

import Footer from '@/components/footer/footer';

const jost = Jost({ subsets: ["latin"] }); // Instantiate the Jost font


export const metadata = {
  title: 'Apostrophe Educational Center',
  description: 'Generated by mia',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="body" className={jost.className}>
        <div className="container">
          <MainHeader />
          <SubmissionFormProvider>
            <div className="main">{children}</div>
          </SubmissionFormProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
